name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Ajusta esto según tu versión de .NET

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: <nombre-de-tu-app> # Reemplaza con el nombre de tu App Service
          publish-url: ${{ secrets.AZURE_WEBAPP_PUBLISH_URL }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_USERNAME }}:${{ secrets.AZURE_WEBAPP_PASSWORD }}
          package: ./publish
